#!/bin/bash
#SBATCH --job-name=sw4_test     ### Job Name
#SBATCH --partition=compute     ### Quality of Service (like a queue in PBS)
#SBATCH --time=0-01:00:00       ### Wall clock time limit in Days-HH:MM:SS
#SBATCH --ntasks=8              ### Nuber of tasks to be launched per Node
#SBATCH --mem-per-cpu=12G
#SBATCH --account=amt

module load sw4/3.0.0
mpirun -np $SLURM_NTASKS sw4 ../examples/llnl-cig-tutorial/LOH-1/LOH.1-h50.in